# Matrices

In [2]:
import numpy as np

## Matriz de ceros

In [3]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

## Matriz de unos

In [4]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

## Forma de la matriz

In [5]:
np.shape(np.ones((3,5)))

(3, 5)

## Suma de matrices

In [24]:
A = np.asarray([[1, 2], [3, 4]])
B = np.asarray([[3, 0], [1, -1]])
print('\n', A, '\n', B)


 [[1 2]
 [3 4]] 
 [[ 3  0]
 [ 1 -1]]


In [17]:
print(A + B)

[[4 2]
 [4 3]]


## Multiplicar matrices

In [20]:
print(A.dot(B))

[[ 5 -2]
 [13 -4]]


## Transpuesta de la matriz

In [22]:
print(A.transpose())

[[1 3]
 [2 4]]


## Traza de la matriz

In [25]:
print(A.trace())

5


## Rango de la matriz

In [26]:
np.linalg.matrix_rank(A)

2

## Potencia de la matriz

In [27]:
np.linalg.matrix_power(A, 5)

array([[1069, 1558],
       [2337, 3406]])

## Determinante de la matriz

In [28]:
np.linalg.det(A)

-2.0000000000000004

## Inversa de la matriz

Si la matriz 

- no es cuadrada o
- tiene un rango menor que el tamaño de la matriz

no es invertible.

In [29]:
np.linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

## Matriz identidad

In [30]:
print(np.linalg.inv(A).dot(A))

[[1.0000000e+00 4.4408921e-16]
 [0.0000000e+00 1.0000000e+00]]
