# Histogramas en Python

## Histogramas con NumPy

In [1]:
import numpy as np

In [21]:
np.set_printoptions(precision=3)

In [22]:
np.random.seed(2019)
x = np.random.laplace(loc=10, scale=3, size=1000)
x[:10]

array([14.935,  9.278, 10.855, 10.968, 14.294,  8.459, 11.555, 14.926,
       14.316,  9.373])

In [6]:
hist, bin_edges = np.histogram(x)

In [7]:
hist  # Observaciones

array([  8,  13,  64, 297, 435, 144,  28,   7,   3,   1], dtype=int64)

In [8]:
bin_edges  # Intervalos de la misma amplitud abiertos por la izda y cerrados por la dcha,
           # excepto el último.

array([-7.648, -3.435,  0.778,  4.992,  9.205, 13.419, 17.632, 21.845,
       26.059, 30.272, 34.486])

In [9]:
hist.size, bin_edges.size

(10, 11)

In [10]:
min_edge = x.min()
max_edge = x.max()

In [13]:
n_bins = 10
bin_edges = np.linspace(start=min_edge, stop=max_edge, num=n_bins + 1, endpoint=True)
bin_edges

array([-7.648, -3.435,  0.778,  4.992,  9.205, 13.419, 17.632, 21.845,
       26.059, 30.272, 34.486])

In [14]:
x = (0, 1, 1, 1, 2, 2, 3, 7, 7, 7, 25)

In [16]:
bcount = np.bincount(x)
bcount

array([1, 3, 2, 1, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1], dtype=int64)

In [17]:
hist, _ = np.histogram(x, range=(0, max(x)), bins=max(x) + 1)

In [18]:
hist

array([1, 3, 2, 1, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1], dtype=int64)

In [19]:
np.array_equal(bcount, hist)

True

In [20]:
dict(zip(np.unique(x), bcount[bcount.nonzero()]))

{0: 1, 1: 3, 2: 2, 3: 1, 7: 3, 25: 1}